# Generated by Django 3.2.9 on 2022-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.EmailField(max_length=254, verbose_name='email address')),
                ('email_body', models.CharField(max_length=1000)),
                ('email_subject', models.CharField(max_length=300)),
            ],
        ),
    ]
