# Generated by Django 4.0.1 on 2022-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticateSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(default='Anmol', max_length=150),
        ),
    ]
